"""usage cost

Revision ID: 1967f795ee07
Revises: 26256efadde0
Create Date: 2026-09-28 11:53:53.454614

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1967f795ee07"
down_revision: str | Sequence[str] | None = "26256efadde0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usage_logs", sa.Column("cost_usd", sa.Numeric(precision=14, scale=8), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_logs", "cost_usd")
    # ### end Alembic commands ###
