"""stable message ordering

Revision ID: e6aa12d63ed4
Revises: 3513f3cf1c4e
Create Date: 2026-09-17 23:07:52.216535

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6aa12d63ed4"
down_revision: str | Sequence[str] | None = "3513f3cf1c4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False)
    )
    op.drop_index(op.f("ix_messages_conversation_created"), table_name="messages")
    op.create_index(
        "ix_messages_conversation_seq", "messages", ["conversation_id", "seq"], unique=False
    )
    op.create_unique_constraint("uq_messages_seq", "messages", ["seq"])
    # now() is the transaction start time, identical for both messages of one exchange;
    # clock_timestamp() is the real wall clock at insert time
    op.alter_column("messages", "created_at", server_default=sa.text("clock_timestamp()"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "created_at", server_default=sa.text("now()"))
    op.drop_constraint("uq_messages_seq", "messages", type_="unique")
    op.drop_index("ix_messages_conversation_seq", table_name="messages")
    op.create_index(
        op.f("ix_messages_conversation_created"),
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.drop_column("messages", "seq")
    # ### end Alembic commands ###
