"""message token usage

Revision ID: e890173f2dc7
Revises: 4ba2877b0404
Create Date: 2026-09-17 22:56:10.341177

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e890173f2dc7"
down_revision: str | Sequence[str] | None = "4ba2877b0404"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("input_tokens", sa.Integer(), nullable=True))
    op.add_column("messages", sa.Column("output_tokens", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "output_tokens")
    op.drop_column("messages", "input_tokens")
    # ### end Alembic commands ###
